apiVersion: v1
kind: Pod
metadata:
  name: wp
spec:
  containers:
  - image: wordpress
    name: wordpress
    env:
    - name: WORDPRESS_DB_PASSWORD
      value: examplepass
    - name: WORDPRESS_DB_HOST
      value: 127.0.0.1
    - name: WORDPRESS_DB_USER
      value: exampleuser
    - name: WORDPRESS_DB_NAME
      value: exampledb
  - image: mysql:8.0
    name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: examplepass
    - name: MYSQL_DATABASE
      value: exampledb
    - name: MYSQL_USER
      value: exampleuser
    - name: MYSQL_PASSWORD
      value: examplepass
    volumeMounts:
    - name: data
      mountPath: /var/lib/mysql
  volumes:
  - name: data
    emptyDir: {}