apiVersion: v1
kind: Pod
metadata:
  name: ynov-pod
spec:
  volumes:
    - name: web-content
      emptyDir: {}

  containers:
    # - name: writer
    #   image: busybox
    #   command:
    #     - sh
    #     - -c
    #     - exit 1
    #     - |
    #       while true; do
    #         echo "<html><body><h1>$(date)</h1><p>Je suis à Ynov Croix</p></body></html>" >> /data/index.html
    #         echo "index.html mis à jour à $(date)"
    #         sleep 3
    #       done
    #   volumeMounts:
    #     - name: web-content
    #       mountPath: /data
    - name: writer
      image: busybox
      command:
        - sh
        - -c
        - |
          echo "writer crash volontaire"
          exit 1
      volumeMounts:
        - name: web-content
          mountPath: /data

    - name: nginx
      image: nginx:1.25
      ports:
        - containerPort: 80
      volumeMounts:
        - name: web-content
          mountPath: /usr/share/nginx/html