apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
    - image: redis:6.2-alpine3.13
      name: redis
      ports:
        - containerPort: 6379
          name: redis
      volumeMounts:
        - mountPath: /data
          name: redis-data
  volumes:
    - name: redis-data
      emptyDir: {}
