apiVersion: v1
kind: Pod
metadata:
  name: vote
  labels:
    app: vote
spec:
  containers:
    - image: mohamed1780/vote
      name: vote
      imagePullPolicy: Always
      ports:
        - containerPort: 5000
          name: vote
